# Generated by Django 3.2.1 on 2021-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khovan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieunhaphang',
            name='nhanvien',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên Kinh doanh(không  điền trường này)'),
        ),
    ]
