# Generated by Django 3.2.1 on 2021-06-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khovan', '0002_phieunhaphang_nhanvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhaphangthukho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongtong', models.IntegerField(default=0, verbose_name='Số Lượng Tổng')),
                ('soluongnhap1', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số Lượng Nhâp Lần Đầu')),
                ('soluongnhap2', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số Lượng Nhâp Lần Hai')),
                ('soluongnhap3', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số Lượng Nhâp Lần Ba')),
                ('daxuly', models.BooleanField(verbose_name='check đã xử lý')),
                ('xacnhan', models.BooleanField(verbose_name='check xác nhận -  không check là hủy ')),
                ('hanghoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khovan.hanghoa', verbose_name='Tên Hàng Hoá')),
                ('sophieunhaphang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khovan.phieunhaphang', verbose_name='Mã Số Nhâp Hàng ')),
            ],
            options={
                'verbose_name': 'NHẬP KHO',
                'verbose_name_plural': 'NHẬP KHO',
            },
        ),
    ]
